---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAstgW3Hr73oOO7bXs6ig/cupYrZT0KJMEwsmcPDVjtcFSOhquhMuX012gV2NDSjYB+cymooDAN5NAKlabhcVAxPrpAG8B91U3dOoPzSBBMcnRIcgaIY0FBOIUm2D6SFOygm0nmWZTMLw5CxEEKtGbixLP2B1qrl3dGnqrr9A5y9r0z77QO65S/MIpuRSBC4sKpOS2DDcRql74ua5NGx7T5dwuNyvao7MJ4LFKpC/VwP0aRrWBAEmx06+vDxijivILK4ds8XfguAM39DvoxBMv2jjsa2MDjMDSnWlDyrKjxJ4t77So0eUh+vWfApMkXwOYxwb70meutGjvkfO6j+y+4RUkaPPRNAnwMHcdo0JR60Fv/hwV9lG0UOIDdwwFbNwan8YNFiiSQm3FATYzivhId7SqIPiNiVVeWp1NSEjCdsnd4bOf+Bgn4pnY3Meu2/a4D60G+VGpgdILlc8//BQh5dupARbUnknuCB8SUGbeduknzrZ+UqI58SFM0Hhv7TtfSLkuKNAA94MLR8i8FOfG4kSuFPYO96uQ7omd1EU2lM8nMXu+FIv6zAtxpL+AciVydBqZAlRN7/ntItCiznyejm7pBv7VfPIR2cYUSNMxXn8g62PzjdsLpmFFuDH3hiHy6zIk6NwoVEQGr71yngEF/E9rMststgxQjJ/waT3vmNXDlXLvkYR8j6CCyhq1mTsLMzjp1HPshVoLr5fEI5qEPdcUHFrc=
  template:
    metadata:
      name: grafana-oauth-secret
      namespace: monitoring
