apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/beeapi

nameSuffix: "-staging"

commonLabels:
  app: beeapi-server-staging

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beeapi-server
      spec:
        selector:
          matchLabels:
            app: beeapi-server-staging
        template:
          metadata:
            labels:
              app: beeapi-server-staging
          spec:
            containers:
              - name: beeapi
                env:
                  - name: SERVER_NAME
                    value: "Ynov-Staging"
                # Staging : ressources réduites intentionnellement
                resources:
                  requests:
                    memory: "32Mi"
                    cpu: "25m"
                  limits:
                    memory: "128Mi"
                    cpu: "100m"
                volumeMounts:
                  - name: puzzles-storage
                    mountPath: /app/puzzles
            volumes:
              - name: puzzles-storage
                persistentVolumeClaim:
                  claimName: puzzles-pvc-staging
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: beeapi-server
      spec:
        selector:
          app: beeapi-server-staging
