apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: algohive-infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Sync wave -2 : l'infra doit être prête avant les apps
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: https://github.com/thfx31/Plank.git
    targetRevision: HEAD
    path: k8s-v2/overlays/production/infrastructure
  destination:
    server: https://kubernetes.default.svc
    namespace: algohive
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
