apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: algohive-monitoring-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    # Sync wave -4 : les secrets doivent exister avant le déploiement du monitoring.
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  source:
    repoURL: https://github.com/thfx31/Plank.git
    targetRevision: HEAD
    path: k8s-v2/overlays/production/monitoring-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
