apiVersion: v1
kind: Service
metadata:
  name: algohive-cache
  namespace: algohive
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: algohive
spec:
  selector:
    app: algohive-cache
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
  type: ClusterIP
