apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../secrets/sealed-secret.yaml
  # En staging, une seule instance BeeAPI suffit
  - beeapi-staging.yaml

# En staging, on override la config pour pointer vers le bon domaine
patches:
  - path: configmap-patch.yaml
