apiVersion: apps/v1
kind: Deployment
metadata:
  name: algohive-client
  namespace: algohive
  labels:
    app.kubernetes.io/name: algohive-client
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: algohive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algohive-client
  template:
    metadata:
      labels:
        app: algohive-client
        app.kubernetes.io/name: algohive-client
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - name: client
          image: ghcr.io/algohive-coding-puzzles/client:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20

          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
