apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config/configmap.yaml
  - infrastructure/postgres
  - infrastructure/redis
  - apps/backend
  - apps/client
  - apps/beehub
