apiVersion: v1
kind: Service
metadata:
  name: beehub
  namespace: algohive
  labels:
    app.kubernetes.io/name: beehub
    app.kubernetes.io/component: admin
    app.kubernetes.io/part-of: algohive
spec:
  selector:
    app: beehub
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beehub-db-pvc
  namespace: algohive
  labels:
    app.kubernetes.io/name: beehub
    app.kubernetes.io/component: admin
    app.kubernetes.io/part-of: algohive
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
