apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Ce kustomization agrège les 4 campus d'un seul coup.
# ArgoCD pointe sur ce dossier et déploie tout.
resources:
  - toulouse
  - montpellier
  - lyon
  - staging
