apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/beeapi

nameSuffix: "-lyon"

commonLabels:
  app: beeapi-server-lyon

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: beeapi-server
      spec:
        selector:
          matchLabels:
            app: beeapi-server-lyon
        template:
          metadata:
            labels:
              app: beeapi-server-lyon
          spec:
            containers:
              - name: beeapi
                env:
                  - name: SERVER_NAME
                    value: "Ynov-Lyon"
                volumeMounts:
                  - name: puzzles-storage
                    mountPath: /app/puzzles
            volumes:
              - name: puzzles-storage
                persistentVolumeClaim:
                  claimName: puzzles-pvc-lyon
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: beeapi-server
      spec:
        selector:
          app: beeapi-server-lyon
