apiVersion: v1
kind: Service
metadata:
  name: beeapi-server
  namespace: algohive
  labels:
    app.kubernetes.io/name: beeapi-server
    app.kubernetes.io/component: catalog
    app.kubernetes.io/part-of: algohive
spec:
  selector:
    app: beeapi-server
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
