apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/beeapi

patches:
  - target:
      kind: Deployment
      name: beeapi-server
    patch: |-
      - op: replace
        path: /metadata/name
        value: beeapi-server-mpl
      - op: replace
        path: /spec/selector/matchLabels/app
        value: beeapi-server-mpl
      - op: replace
        path: /spec/template/metadata/labels/app
        value: beeapi-server-mpl
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: "Ynov-Montpellier"
      - op: replace
        path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
        value: puzzles-pvc-mpl

  - target:
      kind: Service
      name: beeapi-server
    patch: |-
      - op: replace
        path: /metadata/name
        value: beeapi-server-mpl
      - op: replace
        path: /spec/selector/app
        value: beeapi-server-mpl

  - target:
      kind: PersistentVolumeClaim
      name: puzzles-pvc
    patch: |-
      - op: replace
        path: /metadata/name
        value: puzzles-pvc-mpl