apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beehub-db-pvc
  namespace: algohive
  labels:
    app.kubernetes.io/name: beehub
    app.kubernetes.io/component: admin
    app.kubernetes.io/part-of: algohive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: gp3
