apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Hérite de la base
resources:
  - ../../base
  - ../../secrets/sealed-secret.yaml
  # Instances BeeAPI production (4 campus)
  - beeapi-toulouse.yaml
  - beeapi-montpellier.yaml
  - beeapi-lyon.yaml
  - beeapi-staging.yaml

# En production, on peut scaler le backend
patches:
  - path: backend-replicas-patch.yaml
